# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export WORKON_HOME=$HOME/.virtualenvs
export EDITOR="vim"
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc

export NVM_DIR=$HOME/.nvm
export NODE_VERSION=v12.16.1
export PHPENV_ROOT=$HOME/.phpenv
export RBENV_ROOT=$HOME/.rbenv

export GOENV_ROOT=$HOME/.goenv
export GOENV_VERSION=1.11.4
export GOPATH=$HOME/gopath/$GOENV_VERSION

export PYENV_ROOT=$HOME/.pyenv
export PYTHON_VERSION=3.6.10
export PIPENV_IGNORE_VIRTUALENVS=1
export PIPENV_INSTALL_TIMEOUT=9999

# Paths
typeset -gU cdpath fpath mailpath manpath path
typeset -gUT INFOPATH infopath

# Set the list of directories that info searches for manuals.
infopath=(
  /usr/local/share/info
  /usr/share/info
  $infopath
)

# Set the list of directories that man searches for manuals.
manpath=(
  /usr/local/share/man
  /usr/share/man
  $manpath
)

for path_file in /etc/manpaths.d/*(.N); do
  manpath+=($(<$path_file))
done
unset path_file

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
  $HOME/.scripts
  $NVM_DIR/versions/node/$NODE_VERSION/bin
  $GOPATH/bin
  $PHPENV_ROOT/{bin,shims}
  $GOENV_ROOT/{bin,shims}
  $PYENV_ROOT/{bin,shims}
  $RBENV_ROOT/bin
  $path
)

for path_file in /etc/paths.d/*(.N); do
  path+=($(<$path_file))
done
unset path_file
