# zmodload zsh/zprof
# bindkey -v
# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

SPACESHIP_PROMPT_ORDER=(
  # time          # Time stamps section
  # user          # Username section
  dir           # Current directory section
  # host          # Hostname section
  git           # Git section (git_branch + git_status)
  # hg            # Mercurial section (hg_branch  + hg_status)
  # package       # Package version
  # node          # Node.js section
  # ruby          # Ruby section
  # elixir        # Elixir section
  # xcode         # Xcode section
  # swift         # Swift section
  # golang        # Go section
  # php           # PHP section
  # rust          # Rust section
  # haskell       # Haskell Stack section
  # julia         # Julia section
  # docker        # Docker section
  # aws           # Amazon Web Services section
  venv          # virtualenv section
  # conda         # conda virtualenv section
  # pyenv         # Pyenv section
  # dotnet        # .NET section
  # ember         # Ember.js section
  # kubectl       # Kubectl context section
  # terraform     # Terraform workspace section
  # exec_time     # Execution time
  line_sep      # Line break
  # battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  # jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

SPACESHIP_CHAR_SYMBOL="❯ "
SPACESHIP_VI_MODE_COLOR="black"

ZSH_THEME="spaceship"
plugins=(
  archlinux
  # git
  zsh-syntax-highlighting
  zsh-completions
  zsh-autosuggestions
  nvm
  vi-mode
)

source $ZSH/oh-my-zsh.sh
autoload -Uz compinit

# check cached dump once a day
for dump in ~/.zcompdump(N.mh+24); do
   compinit
done
compinit -C

# source <(cat ~/.oh-my-zsh/custom/alias/*)

eval `dircolors ~/.dir_colors`

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

if command -v phpenv 1>/dev/null 2>&1; then
  eval "$(phpenv init -)"
fi

# zprof