if [[ -v ZSH_PROF ]]; then
  zmodload zsh/zprof
fi

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME=''
plugins=(git zsh-syntax-highlighting zsh-completions zsh-autosuggestions kubectl kops vi-mode)

fpath=(~/.zsh/completion $fpath)

source $ZSH/oh-my-zsh.sh
autoload -U compinit && compinit

autoload -U promptinit; promptinit
prompt pure

# source <(cat ~/.oh-my-zsh/custom/alias/*)

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval `dircolors ~/.dir_colors/dircolors`

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

if command -v rbenv 1>/dev/null 2>&1; then
  eval "$(rbenv init -)"
fi

if command -v goenv 1>/dev/null 2>&1; then
  eval "$(goenv init -)"
fi
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
