if [[ -v ZSH_PROF ]]; then
  zmodload zsh/zprof
fi

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME=''
plugins=(git zsh-syntax-highlighting zsh-completions kubectl kops vi-mode)

fpath=(~/.zsh/completion $fpath)

source $ZSH/oh-my-zsh.sh
autoload -U compinit && compinit

autoload -U promptinit; promptinit
prompt pure

source <(cat ~/.oh-my-zsh/custom/alias/*)

# Virtualenvwrapper Configuration
source /usr/local/bin/virtualenvwrapper_lazy.sh
